import type { SectorMeta } from '../types'

export const SECTORS: SectorMeta[] = [
  {
    id: 'water',
    label: 'Water & Sanitation',
    shortLabel: 'Water',
    tagline: 'JJM, AMRUT 2.0, NMCG, state water boards — DPR, PMC and TPI consultancies',
    accent: 'bg-sky-700',
    accentSoft: 'bg-sky-50 border-sky-200',
    accentText: 'text-sky-800',
    accentHex: '#0369a1',
    icon: '💧',
  },
  {
    id: 'power',
    label: 'Power & Energy',
    shortLabel: 'Power',
    tagline: 'RDSS PMA, owner’s engineer, renewables advisory across discoms and CPSEs',
    accent: 'bg-amber-600',
    accentSoft: 'bg-amber-50 border-amber-200',
    accentText: 'text-amber-800',
    accentHex: '#d97706',
    icon: '⚡',
  },
  {
    id: 'road',
    label: 'Roads & Highways',
    shortLabel: 'Roads',
    tagline: 'NHAI / MoRTH Authority’s Engineer, DPR, IE and supervision consultancies',
    accent: 'bg-emerald-700',
    accentSoft: 'bg-emerald-50 border-emerald-200',
    accentText: 'text-emerald-800',
    accentHex: '#047857',
    icon: '🛣️',
  },
  {
    id: 'railway',
    label: 'Railways & Metro',
    shortLabel: 'Rail',
    tagline: 'RVNL, DFCCIL, NHSRCL, metro DDC/GC and station redevelopment advisory',
    accent: 'bg-indigo-700',
    accentSoft: 'bg-indigo-50 border-indigo-200',
    accentText: 'text-indigo-800',
    accentHex: '#4338ca',
    icon: '🚆',
  },
  {
    id: 'urban',
    label: 'Urban & Smart Cities',
    shortLabel: 'Urban',
    tagline: 'Smart Cities Mission PMC, PMAY-U, master plans and municipal infra advisory',
    accent: 'bg-rose-700',
    accentSoft: 'bg-rose-50 border-rose-200',
    accentText: 'text-rose-800',
    accentHex: '#be123c',
    icon: '🏙️',
  },
  {
    id: 'ports',
    label: 'Ports & Waterways',
    shortLabel: 'Ports',
    tagline: 'Sagarmala, major port authorities and IWAI — feasibility, master plan, PPP advisory',
    accent: 'bg-cyan-700',
    accentSoft: 'bg-cyan-50 border-cyan-200',
    accentText: 'text-cyan-800',
    accentHex: '#0e7490',
    icon: '⚓',
  },
  {
    id: 'aviation',
    label: 'Airports & Aviation',
    shortLabel: 'Aviation',
    tagline: 'AAI PMC/DPR, UDAN airports, greenfield feasibility and privatization advisory',
    accent: 'bg-violet-700',
    accentSoft: 'bg-violet-50 border-violet-200',
    accentText: 'text-violet-800',
    accentHex: '#6d28d9',
    icon: '✈️',
  },
]

export function sectorMeta(id: string): SectorMeta {
  return SECTORS.find((s) => s.id === id) ?? SECTORS[0]
}
